### ISSUE TITLE
toolbar controls can not be disabled

### ISSUE THREAD

**Issue by steffi80** [foex-open-source/fos-interactive-grid-add-button#5]
In the grid attributes under toolbar I have disabled the search field and the actions menu. When I add a button to the Edit & save group with the plugin, the search field and actions menu are shown nevertheless. Is there a way I can still hide these when adding a button?

**Comment by stefandobre** [comment]
Hi Steffi,

I was able to reproduce this bug. Will update this thread once it's fixed.

**Comment by stefandobre** [comment]
Fixed in FOS version 20.2

This turned out to be more of an APEX inconsistency.
Whenever the toolbar is refreshed, some information, such as the state of the search bar gets lost.

I built in a workaround, which resets some things after toolbar refresh.
You can download the latest version of the demo app and all plug-ins [here](https://fos.world/).

**Comment by steffi80** [comment]
Hi Stefan! Thanks for the fast help, works great!
